name: .NET Package test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
    DOTNETVERSION: 6.0.300
jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '${{env.DOTNETVERSION}}'
    - name: Install .NET MAUI
      shell: pwsh
      run: |
          & dotnet nuget locals all --clear
          & dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          # & dotnet workload install android ios maccatalyst tvos macos maui wasm-tools maui-maccatalyst --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    - name: Restore dependencies
      run: |
          & cd MauiAudio
          & dotnet restore
    - name: Build
      run: |
          & cd MauiAudio
          & dotnet pack --no-restore --configuration Release
